import { RecoveryEvent, Customer, AuditLogEntry, AIDecision, MerchantPolicy, KPIStats } from '../types';

export const initialKPIs: KPIStats = {
  revenueAtRisk: 245000,
  revenueRecovered: 94500,
  recoveryAttempts: 60,
  successfulRecoveries: 38,
  recoveryRate: 63.3,
};

export const initialPolicy: MerchantPolicy = {
  maxAutoRetries: 2,
  maxAutoRecoveryAmount: 10000,
  recoveryWindowHours: 24,
  requireApprovalAboveAmount: 5000,
  enableAutoRetry: true,
  enableCustomerReminder: true,
  applyDiscount: false,
  altPaymentMethod: true,
  autoRecoveryEnabled: true,
};

export const initialEvents: RecoveryEvent[] = [
  {
    id: 'EVT-1024',
    orderId: 'ORD-1024',
    customerName: 'Arjun Kumar',
    customerEmail: 'arjun.k@example.com',
    amount: 4999,
    currency: 'INR',
    productName: 'Sony WH-1000XM5 Wireless Headphones',
    riskLevel: 'Low',
    failureReason: 'Authentication Failure (3DS Timeout)',
    aiRecommendation: 'Retry Payment',
    aiConfidence: 91,
    aiReasoning: 'Customer has 5 previous successful payments. No recent failed attempts. Transaction amount is below merchant auto-recovery limit.',
    status: 'Recovered',
    policyStatus: 'Allowed',
    attempts: 1,
    maxAttempts: 2,
    createdAt: 'Today, 10:31 AM',
    updatedAt: 'Today, 10:34 AM',
    revenueRecovered: 4999,
    timeline: [
      { time: '10:31 AM', title: 'Payment Failed', description: 'Bank declined transaction (3DS authentication timeout)', type: 'failed' },
      { time: '10:31 AM', title: 'Revenue Risk Detected', description: 'Risk detector flagged ₹4,999 at risk', type: 'diagnosis' },
      { time: '10:31 AM', title: 'AI Diagnosis Completed', description: 'Transient OTP authentication failure detected', type: 'diagnosis' },
      { time: '10:32 AM', title: 'Recovery Recommended', description: 'Smart Retry scheduled for high confidence score (91%)', type: 'recommendation' },
      { time: '10:32 AM', title: 'Policy Engine Validated', description: 'Action complies with ₹10,000 auto limit & attempt cap', type: 'approval' },
      { time: '10:33 AM', title: 'Customer Approved', description: 'Customer confirmed payment retry via SMS link', type: 'approval' },
      { time: '10:34 AM', title: 'Payment Recovered', description: 'Razorpay Test Payment executed successfully', type: 'recovered' },
    ],
  },
  {
    id: 'EVT-1025',
    orderId: 'ORD-1025',
    customerName: 'Priya Sharma',
    customerEmail: 'priya.sharma@example.com',
    amount: 14999,
    currency: 'INR',
    productName: 'Apple Watch SE 40mm',
    riskLevel: 'High',
    failureReason: 'Insufficient Funds',
    aiRecommendation: 'Send Payment Reminder with UPI Option',
    aiConfidence: 78,
    aiReasoning: 'High-value transaction above ₹10,000 threshold. Requires manual merchant validation or scheduled UPI prompt.',
    status: 'Pending',
    policyStatus: 'Approval Required',
    attempts: 0,
    maxAttempts: 2,
    createdAt: 'Today, 09:15 AM',
    updatedAt: 'Today, 09:15 AM',
    revenueRecovered: 0,
    timeline: [
      { time: '09:15 AM', title: 'Payment Failed', description: 'Card issuer returned insufficient funds code', type: 'failed' },
      { time: '09:15 AM', title: 'Revenue Risk Detected', description: 'High priority risk flag ₹14,999', type: 'diagnosis' },
      { time: '09:16 AM', title: 'AI Diagnosis Completed', description: 'Recommend sending payment reminder with UPI payment link', type: 'recommendation' },
      { time: '09:16 AM', title: 'Policy Check', description: 'Requires approval (amount exceeds ₹10,000 threshold)', type: 'approval' },
    ],
  },
  {
    id: 'EVT-1026',
    orderId: 'ORD-1026',
    customerName: 'Rajesh Verma',
    customerEmail: 'rajesh.verma@example.com',
    amount: 2499,
    currency: 'INR',
    productName: 'Logitech MX Master 3S',
    riskLevel: 'Low',
    failureReason: 'Network Gateway Error',
    aiRecommendation: 'Instant Intelligent Retry',
    aiConfidence: 96,
    aiReasoning: 'Temporary gateway connection drops detected across acquiring bank. Instant retry has 96% success probability.',
    status: 'Recovered',
    policyStatus: 'Allowed',
    attempts: 1,
    maxAttempts: 2,
    createdAt: 'Today, 08:42 AM',
    updatedAt: 'Today, 08:43 AM',
    revenueRecovered: 2499,
    timeline: [
      { time: '08:42 AM', title: 'Payment Failed', description: 'Acquiring bank timeout (504 Gateway Error)', type: 'failed' },
      { time: '08:42 AM', title: 'AI Diagnosis', description: 'Transient network anomaly', type: 'diagnosis' },
      { time: '08:43 AM', title: 'Auto-Retry Success', description: 'Payment recovered automatically in 45 seconds', type: 'recovered' },
    ],
  },
  {
    id: 'EVT-1027',
    orderId: 'ORD-1027',
    customerName: 'Sneha Patel',
    customerEmail: 'sneha.p@example.com',
    amount: 32000,
    currency: 'INR',
    productName: 'Dell UltraSharp 27" 4K Monitor',
    riskLevel: 'High',
    failureReason: 'Card Limit Exceeded & Fraud Alert',
    aiRecommendation: 'Escalate to Merchant Support',
    aiConfidence: 64,
    aiReasoning: 'Multiple failed attempts across 2 separate cards. High risk of fraud or cardholder dispute.',
    status: 'Escalated',
    policyStatus: 'Blocked',
    attempts: 2,
    maxAttempts: 2,
    createdAt: 'Yesterday, 04:20 PM',
    updatedAt: 'Yesterday, 04:35 PM',
    revenueRecovered: 0,
    timeline: [
      { time: '04:20 PM', title: 'Payment Failed', description: 'Card limit exceeded on primary card', type: 'failed' },
      { time: '04:25 PM', title: 'Retry Failed', description: 'Secondary card blocked by issuing bank', type: 'failed' },
      { time: '04:35 PM', title: 'Escalated', description: 'Policy engine blocked further auto retries', type: 'escalated' },
    ],
  },
  {
    id: 'EVT-1028',
    orderId: 'ORD-1028',
    customerName: 'Ananya Sen',
    customerEmail: 'ananya.s@example.com',
    amount: 1850,
    currency: 'INR',
    productName: 'Ergonomic Memory Foam Cushion',
    riskLevel: 'Low',
    failureReason: 'Checkout Abandoned after payment error',
    aiRecommendation: 'Send Automated WhatsApp Checkout Recovery Link',
    aiConfidence: 88,
    aiReasoning: 'Customer abandoned cart immediately following card OTP error. High intent customer.',
    status: 'Recoverable',
    policyStatus: 'Allowed',
    attempts: 0,
    maxAttempts: 2,
    createdAt: 'Yesterday, 02:10 PM',
    updatedAt: 'Yesterday, 02:10 PM',
    revenueRecovered: 0,
    timeline: [
      { time: '02:10 PM', title: 'Checkout Abandoned', description: 'User left checkout after card processing delay', type: 'failed' },
      { time: '02:11 PM', title: 'AI Diagnosis', description: 'Checkout abandonment due to payment friction', type: 'diagnosis' },
    ],
  },
];

export const initialCustomers: Customer[] = [
  {
    id: 'CUST-101',
    name: 'Arjun Kumar',
    email: 'arjun.k@example.com',
    phone: '+91 98765 43210',
    ordersCount: 14,
    totalSpend: 82400,
    failedPaymentsCount: 1,
    recoveryAttempts: 1,
    recoveredRevenue: 4999,
    status: 'Healthy',
    createdAt: '2025-11-12',
    recentOrders: [
      { id: 'ORD-1024', product: 'Sony WH-1000XM5', amount: 4999, date: '2026-08-22', status: 'Recovered' },
      { id: 'ORD-0988', product: 'Mechanical Keyboard', amount: 8999, date: '2026-07-14', status: 'Paid' },
      { id: 'ORD-0842', product: 'USB-C Docking Station', amount: 6499, date: '2026-05-20', status: 'Paid' },
    ],
  },
  {
    id: 'CUST-102',
    name: 'Priya Sharma',
    email: 'priya.sharma@example.com',
    phone: '+91 98123 45678',
    ordersCount: 6,
    totalSpend: 45000,
    failedPaymentsCount: 2,
    recoveryAttempts: 1,
    recoveredRevenue: 0,
    status: 'Medium Risk',
    createdAt: '2026-01-05',
    recentOrders: [
      { id: 'ORD-1025', product: 'Apple Watch SE 40mm', amount: 14999, date: '2026-08-22', status: 'Pending Recovery' },
      { id: 'ORD-0920', product: 'AirPods Pro', amount: 19900, date: '2026-06-18', status: 'Paid' },
    ],
  },
  {
    id: 'CUST-103',
    name: 'Rajesh Verma',
    email: 'rajesh.verma@example.com',
    phone: '+91 99000 11223',
    ordersCount: 22,
    totalSpend: 142000,
    failedPaymentsCount: 3,
    recoveryAttempts: 3,
    recoveredRevenue: 12499,
    status: 'Healthy',
    createdAt: '2024-09-30',
    recentOrders: [
      { id: 'ORD-1026', product: 'Logitech MX Master 3S', amount: 2499, date: '2026-08-22', status: 'Recovered' },
      { id: 'ORD-0955', product: 'Dual Monitor Arm', amount: 4500, date: '2026-07-02', status: 'Paid' },
    ],
  },
  {
    id: 'CUST-104',
    name: 'Sneha Patel',
    email: 'sneha.p@example.com',
    phone: '+91 97777 88899',
    ordersCount: 2,
    totalSpend: 32000,
    failedPaymentsCount: 2,
    recoveryAttempts: 2,
    recoveredRevenue: 0,
    status: 'High Risk',
    createdAt: '2026-08-10',
    recentOrders: [
      { id: 'ORD-1027', product: 'Dell UltraSharp 27" 4K', amount: 32000, date: '2026-08-21', status: 'Escalated' },
    ],
  },
];

export const initialDecisions: AIDecision[] = [
  {
    id: 'DEC-4821',
    orderId: 'ORD-1024',
    customerName: 'Arjun Kumar',
    diagnosis: 'Authentication Failure (3DS Timeout)',
    recommendation: 'Retry Payment via Customer Prompt',
    confidence: 91,
    reason: 'Customer has strong previous payment history and transaction is within merchant policy limits (₹4,999 <= ₹10,000).',
    policyValid: true,
    policyDetails: 'Within max retries (0/2) and under auto-recovery cap',
    status: 'Approved',
    createdAt: '10:31:45 AM',
  },
  {
    id: 'DEC-4822',
    orderId: 'ORD-1025',
    customerName: 'Priya Sharma',
    diagnosis: 'Insufficient Funds on Credit Card',
    recommendation: 'Send Alternate Payment (UPI QR) Link',
    confidence: 78,
    reason: 'UPI conversion rate is 84% for insufficient funds error codes. High order value requires policy check.',
    policyValid: false,
    policyDetails: 'Exceeds auto-approval limit of ₹10,000 (Amount: ₹14,999)',
    status: 'Pending',
    createdAt: '09:16:02 AM',
  },
  {
    id: 'DEC-4823',
    orderId: 'ORD-1026',
    customerName: 'Rajesh Verma',
    diagnosis: 'Acquiring Bank Network Timeout',
    recommendation: 'Instant Intelligent Retry',
    confidence: 96,
    reason: 'Systemic bank error resolved within 30 seconds. Automatic retry highly recommended.',
    policyValid: true,
    policyDetails: 'Valid under automated retry rules',
    status: 'Executed',
    createdAt: '08:42:15 AM',
  },
];

export const initialAuditLogs: AuditLogEntry[] = [
  {
    id: 'AUD-9011',
    timestamp: '2026-08-22 10:34:12',
    eventId: 'EVT-1024',
    orderId: 'ORD-1024',
    action: 'Payment Recovered',
    reason: 'Razorpay Test Payment successful following customer approval',
    amount: 4999,
    policyResult: 'Allowed',
    actor: 'Customer',
    status: 'Completed',
    details: {
      what: 'Executed payment retry via Razorpay Test API',
      why: 'Customer approved 3DS retry link sent by recovery agent',
      who: 'Customer (Arjun Kumar via SMS link)',
      policyApplied: 'Policy #POL-01: Max retries 2, Cap ₹10,000',
      amountInvolved: '₹4,999',
      result: 'SUCCESS - ₹4,999 revenue recovered',
    },
  },
  {
    id: 'AUD-9010',
    timestamp: '2026-08-22 10:32:05',
    eventId: 'EVT-1024',
    orderId: 'ORD-1024',
    action: 'Policy Engine Validation',
    reason: 'Validated recovery action against merchant risk rules',
    amount: 4999,
    policyResult: 'Allowed',
    actor: 'System',
    status: 'Completed',
    details: {
      what: 'Validated AI recommendation #DEC-4821 against merchant policies',
      why: 'Mandatory safeguard verification before execution',
      who: 'Policy Engine v2.4',
      policyApplied: 'Rule #3: Single transaction limit check',
      amountInvolved: '₹4,999',
      result: 'PASSED - Action approved for execution',
    },
  },
  {
    id: 'AUD-9009',
    timestamp: '2026-08-22 10:31:45',
    eventId: 'EVT-1024',
    orderId: 'ORD-1024',
    action: 'AI Diagnosis & Recommendation',
    reason: 'Authentication failure detected with 91% confidence score',
    amount: 4999,
    policyResult: 'Allowed',
    actor: 'AI Agent',
    status: 'Completed',
    details: {
      what: 'AI Agent analyzed transaction failure telemetry',
      why: 'Detected recoverable 3DS OTP timeout anomaly',
      who: 'RazorRecover AI Agent v1.0',
      policyApplied: 'N/A (Diagnosis phase)',
      amountInvolved: '₹4,999',
      result: 'Generated Recommendation: Retry Payment',
    },
  },
  {
    id: 'AUD-9008',
    timestamp: '2026-08-22 09:16:02',
    eventId: 'EVT-1025',
    orderId: 'ORD-1025',
    action: 'Policy Engine Block (Approval Required)',
    reason: 'Transaction amount ₹14,999 exceeds auto limit ₹10,000',
    amount: 14999,
    policyResult: 'Blocked',
    actor: 'System',
    status: 'Pending',
    details: {
      what: 'Policy engine intercepted recovery recommendation',
      why: 'Transaction value exceeds merchant automated ceiling',
      who: 'Policy Engine v2.4',
      policyApplied: 'Rule #1: Require merchant approval above ₹10,000',
      amountInvolved: '₹14,999',
      result: 'BLOCKED AUTO-EXECUTION - Moved to Merchant Approval Queue',
    },
  },
];
